In [1]:
import os
import pandas as pd
from micom.viz import plot_growth
from micom.workflows import grow

from micom.qiime_formats import load_qiime_medium
from micom.data import test_medium
from micom.workflows import build, build_database

In [2]:
out_folder = "../data/Lloyd-Price_2019_HMP2IBD/SAMN07510030/simulations/"

In [3]:
tax = pd.read_csv("../data/Lloyd-Price_2019_HMP2IBD/SAMN07510030/sample_manifest.csv")
tax

,Unnamed: 0,id,kingdom,phylum,class,order,family,genus,species,file,sample_id,abundance
0,0,spire_mag_00366776,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Rikenellaceae,Alistipes,Alistipes putredinis,/home/alexandre/Documents/projects/micro_fr_pr...,SAMN07510030,389.802726
1,1,spire_mag_00366781,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides uniformis,/home/alexandre/Documents/projects/micro_fr_pr...,SAMN07510030,252.655467
2,2,spire_mag_00366783,Bacteria,Firmicutes_A,Clostridia,Lachnospirales,Lachnospiraceae,Agathobacter,Agathobacter rectalis,/home/alexandre/Documents/projects/micro_fr_pr...,SAMN07510030,357.541807

In [4]:
manifest = build(
    taxonomy=tax,
    out_folder=f"{out_folder}",
    model_db=None,
    cutoff=0.0001,
    threads=2,
)

manifest

[04/10/25 09:47:25] WARNING  Found existing models for 1 samples. Will skip those. Delete the output    ]8;id=720760;file:///home/alexandre/miniconda3/envs/mtgw/lib/python3.9/site-packages/micom/workflows/build.py\build.py]8;;\:]8;id=352529;file:///home/alexandre/miniconda3/envs/mtgw/lib/python3.9/site-packages/micom/workflows/build.py#98\98]8;;\
                             folder if you would like me to rebuild them.

Output()

Set parameter Username
Set parameter LicenseID to value 2582980
Academic license - for non-commercial use only - expires 2025-11-13
Read LP format model from file /tmp/tmp_3bueynw.lp
Reading time = 0.01 seconds
: 1989 rows, 4791 columns, 18333 nonzeros

      sample_id                 file
0  SAMN07510030  SAMN07510030.pickle

In [5]:
medium = load_qiime_medium("../data/western_diet_gut.qza")
# medium = load_qiime_medium(test_medium)
medium

                flux  dilution metabolite    reaction
reaction
EX_fru_m    0.014899     0.100      fru_m    EX_fru_m
EX_glc_m    0.014899     0.100      glc_m    EX_glc_m
EX_gal_m    0.014899     0.100      gal_m    EX_gal_m
EX_man_m    0.014899     0.100      man_m    EX_man_m
EX_mnl_m    0.014899     0.100      mnl_m    EX_mnl_m
...              ...       ...        ...         ...
EX_glu_D_m  0.100000     0.100    glu_D_m  EX_glu_D_m
EX_gthrd_m  0.100000     0.100    gthrd_m  EX_gthrd_m
EX_h2_m     0.100000     0.100       h2_m     EX_h2_m
EX_no2_m    0.100000     0.100      no2_m    EX_no2_m
EX_o2_m     0.001000     0.001       o2_m     EX_o2_m

[170 rows x 4 columns]

In [6]:
res = grow(
    manifest,
    model_folder=out_folder,
    medium=medium,
    tradeoff=1.0,
    threads=2,
)

res

Output()

Set parameter Username
Set parameter LicenseID to value 2582980
Academic license - for non-commercial use only - expires 2025-11-13
Read LP format model from file /tmp/tmpqng5zvxi.lp
Reading time = 0.01 seconds
: 1989 rows, 4791 columns, 18333 nonzeros

GrowthResults(growth_rates=                    abundance  growth_rate  reactions  metabolites  \
compartments
spire_mag_00366776   0.389803          0.0        973          766
spire_mag_00366781   0.252655          0.0        500          429
spire_mag_00366783   0.357542          0.0        702          570

                                 taxon  tradeoff     sample_id
compartments
spire_mag_00366776  spire_mag_00366776       1.0  SAMN07510030
spire_mag_00366781  spire_mag_00366781       1.0  SAMN07510030
spire_mag_00366783  spire_mag_00366783       1.0  SAMN07510030  , exchanges=Empty DataFrame
Columns: [taxon, sample_id, tolerance, reaction, flux, abundance, metabolite, direction]
Index: [], annotations=                   metabolite  \
reaction
EX_26dap__M_e      26dap__M_e
EX_2m35mdntha_e  2m35mdntha_e
EX_2pglyc_e          2pglyc_e
EX_35dnta_e          35dnta_e
EX_4abz_e              4abz_e
...                       ...
EX_prohisglu_m    prohisglu_m
EX_raffin_m          raffin_m
EX_so3_m                so3_m
EX_tre6p_m            tre6p_m
EX_tsul_m              tsul_m

                                                              name  \
reaction
EX_26dap__M_e                        Meso-2,6-Diaminoheptanedioate
EX_2m35mdntha_e  N  2 methyl 3 5 dinitrophenyl  4 methyl 3 5 di...
EX_2pglyc_e                                     2-Phosphoglycolate
EX_35dnta_e                        N N bis 3 5 dinitrotolyl  amine
EX_4abz_e                                          4-Aminobenzoate
...                                                            ...
EX_prohisglu_m              Proline-histidine-glutamine tripeptide
EX_raffin_m                                    Raffinose C18H32O16
EX_so3_m                                                   Sulfite
EX_tre6p_m                      Alpha,alpha'-Trehalose 6-phosphate
EX_tsul_m                                              Thiosulfate

                 molecular_weight  C_number  N_number          sbo  \
reaction
EX_26dap__M_e          190.197060         7         2  SBO:0000247
EX_2m35mdntha_e         15.014640         0         1  SBO:0000247
EX_2pglyc_e            153.007441         2         0  SBO:0000247
EX_35dnta_e             15.014640         0         1  SBO:0000247
EX_4abz_e              136.128040         7         1  SBO:0000247
...                           ...       ...       ...          ...
EX_prohisglu_m         398.391060        16         5  SBO:0000247
EX_raffin_m            504.437080        18         0  SBO:0000247
EX_so3_m                80.063200         0         0  SBO:0000247
EX_tre6p_m             420.260501        12         0  SBO:0000247
EX_tsul_m              112.128200         0         0  SBO:0000247

                        kegg.compound  \
reaction
EX_26dap__M_e                  C00680
EX_2m35mdntha_e                   NaN
EX_2pglyc_e                    C00988
EX_35dnta_e                       NaN
EX_4abz_e                      C00568
...                               ...
EX_prohisglu_m                    NaN
EX_raffin_m                    C00492
EX_so3_m         ['C00094', 'C11481']
EX_tre6p_m                     C00689
EX_tsul_m        ['C00320', 'C05529']

                                                             chebi  \
reaction
EX_26dap__M_e    ['CHEBI:10598', 'CHEBI:12822', 'CHEBI:12823', ...
EX_2m35mdntha_e                                                NaN
EX_2pglyc_e      ['CHEBI:11652', 'CHEBI:1268', 'CHEBI:17150', '...
EX_35dnta_e                                                    NaN
EX_4abz_e        ['CHEBI:113372', 'CHEBI:11959', 'CHEBI:1783', ...
...                                                            ...
EX_prohisglu_m                                                 NaN
EX_raffin_m      ['CHEBI:15015', 'CHEBI:16634', 'CHEBI:26521', ...
EX_so3_m         ['CHEBI:13367', 'CHEBI:15139', 'CHEBI:17137', ...
EX_tre6p_m       ['CHEBI:10201', 'CHEBI:12285', 'CHEBI:15252', ...
EX_tsul_m        ['CHEBI:15242', 'CHEBI:16094', 'CHEBI:26977', ...

                                    inchikey  \
reaction
EX_26dap__M_e    GMKMEZVLHJARHF-SYDPRGILSA-N
EX_2m35mdntha_e                          NaN
EX_2pglyc_e      ASCFNMCAHFUBCO-UHFFFAOYSA-K
EX_35dnta_e                              NaN
EX_4abz_e        ALYNCZNDIQEVRV-UHFFFAOYSA-M
...                                      ...
EX_prohisglu_m                           NaN
EX_raffin_m      MUPFEKGTMRGPLJ-ZQSKZDJDSA-N
EX_so3_m         LSNNMFCWUKXFEE-UHFFFAOYSA-L
EX_tre6p_m       LABSPYBHMPDTEL-LIZSDCNHSA-L
EX_tsul_m        DHCDFWKWKRSZHF-UHFFFAOYSA-M

                                                  biocyc metanetx.chemical  \
reaction
EX_26dap__M_e                  META:MESO-DIAMINOPIMELATE           MNXM529
EX_2m35mdntha_e                                      NaN               NaN
EX_2pglyc_e                                  META:CPD-67          MNXM2074
EX_35dnta_e                                          NaN               NaN
EX_4abz_e                          META:P-AMINO-BENZOATE           MNXM421
...                                                  ...               ...
EX_prohisglu_m                                       NaN               NaN
EX_raffin_m                                META:CPD-1099           MNXM621
EX_so3_m         ['META:H2SO3', 'META:HSO3', 'META:SO3']        MNXM105630
EX_tre6p_m                             META:TREHALOSE-6P           MNXM448
EX_tsul_m                                      META:S2O3           MNXM323

                seed.compound  \
reaction
EX_26dap__M_e        cpd00516
EX_2m35mdntha_e           NaN
EX_2pglyc_e          cpd00727
EX_35dnta_e               NaN
EX_4abz_e            cpd00443
...                       ...
EX_prohisglu_m            NaN
EX_raffin_m          cpd00382
EX_so3_m             cpd00081
EX_tre6p_m           cpd00523
EX_tsul_m            cpd00268

                                                              hmdb kegg.drug  \
reaction
EX_26dap__M_e                                                  NaN       NaN
EX_2m35mdntha_e                                                NaN       NaN
EX_2pglyc_e                             ['HMDB00816', 'HMDB60148']       NaN
EX_35dnta_e                                                    NaN       NaN
EX_4abz_e                                                HMDB01392    D02456
...                                                            ...       ...
EX_prohisglu_m                                                 NaN       NaN
EX_raffin_m                                              HMDB03213       NaN
EX_so3_m         ['HMDB00240', 'HMDB01033', 'HMDB03008', 'HMDB3...       NaN
EX_tre6p_m                                               HMDB01124       NaN
EX_tsul_m                               ['HMDB00257', 'HMDB60293']       NaN

                      reactome lipidmaps kegg.glycan         reaction
reaction
EX_26dap__M_e              NaN       NaN         NaN    EX_26dap__M_e
EX_2m35mdntha_e            NaN       NaN         NaN  EX_2m35mdntha_e
EX_2pglyc_e                NaN       NaN         NaN      EX_2pglyc_e
EX_35dnta_e                NaN       NaN         NaN      EX_35dnta_e
EX_4abz_e                  NaN       NaN         NaN        EX_4abz_e
...                        ...       ...         ...              ...
EX_prohisglu_m             NaN       NaN         NaN   EX_prohisglu_m
EX_raffin_m                NaN       NaN      G00249      EX_raffin_m
EX_so3_m                   NaN       NaN         NaN         EX_so3_m
EX_tre6p_m        R-ALL-868701       NaN      G09795       EX_tre6p_m
EX_tsul_m        R-ALL-1614595       NaN         NaN        EX_tsul_m

[440 rows x 18 columns])

In [ ]:
pl = plot_growth(res, filename=f"{out_folder}growth_rates.html")

In [8]:
import pandas as pd

candidate_medium = pd.DataFrame({"reaction": ["EX_glc__D_m", "EX_o2_m"], "flux": [10, 20]})
candidate_medium

      reaction  flux
0  EX_glc__D_m    10
1      EX_o2_m    20

In [10]:
from micom.workflows import complete_community_medium

medium = complete_community_medium(manifest, model_folder=out_folder, medium=candidate_medium,
                    community_growth=0.1, min_growth=0.01,
                    max_import=10, threads=2)
medium

Output()

Set parameter Username
Set parameter LicenseID to value 2582980
Academic license - for non-commercial use only - expires 2025-11-13
Read LP format model from file /tmp/tmp_yrblaxg.lp
Reading time = 0.01 seconds
: 1989 rows, 4791 columns, 18333 nonzeros

,reaction,metabolite,description,flux
0,EX_26dap__M_m,26dap__M_m,"Meso-2,6-Diaminoheptanedioate",0.009358
1,EX_2ameph_m,2ameph_m,2-Aminoethylphosphonate,0.001171
2,EX_LalaDgluMdap_m,LalaDgluMdap_m,"L-alanine-D-glutamate-meso-2,6-diaminoheptaned...",0.000253
3,EX_abt__D_m,abt__D_m,D-Arabitol,0.025084
4,EX_acmana_m,acmana_m,N-Acetyl-D-mannosamine,0.000505
...,...,...,...,...
64,EX_uaccg_m,uaccg_m,UDP-N-acetyl-3-O-(1-carboxyvinyl)-D-glucosamine,0.009747
65,EX_udcpp_m,udcpp_m,Undecaprenyl phosphate,0.010000
66,EX_ump_m,ump_m,UMP C9H11N2O9P,0.019918
67,EX_val__L_m,val__L_m,L-Valine,0.043454
68,EX_zn2_m,zn2_m,Zinc,0.000034

In [11]:
res = grow(
    manifest,
    model_folder=out_folder,
    medium=medium,
    tradeoff=1.0,
    threads=2,
)

res

Output()

Set parameter Username
Set parameter LicenseID to value 2582980
Academic license - for non-commercial use only - expires 2025-11-13
Read LP format model from file /tmp/tmpxsqj6z4_.lp
Reading time = 0.01 seconds
: 1989 rows, 4791 columns, 18333 nonzeros

GrowthResults(growth_rates=                    abundance  growth_rate  reactions  metabolites  \
compartments
spire_mag_00366776   0.389803     0.009999        973          766
spire_mag_00366781   0.252655     0.000000        500          429
spire_mag_00366783   0.357542     0.261721        702          570

                                 taxon  tradeoff     sample_id
compartments
spire_mag_00366776  spire_mag_00366776       1.0  SAMN07510030
spire_mag_00366781  spire_mag_00366781       1.0  SAMN07510030
spire_mag_00366783  spire_mag_00366783       1.0  SAMN07510030  , exchanges=                  taxon     sample_id  tolerance          reaction  \
0    spire_mag_00366776  SAMN07510030   0.000001  EX_fe3pyovd_kt_e
1    spire_mag_00366776  SAMN07510030   0.000001        EX_uaccg_e
2    spire_mag_00366776  SAMN07510030   0.000001            EX_k_e
3    spire_mag_00366776  SAMN07510030   0.000001    EX_lysglugly_e
5    spire_mag_00366776  SAMN07510030   0.000001       EX_asn__L_e
..                  ...           ...        ...               ...
569              medium  SAMN07510030   0.000001          EX_zn2_m
573              medium  SAMN07510030   0.000001       EX_lys__L_m
577              medium  SAMN07510030   0.000001        EX_udcpp_m
578              medium  SAMN07510030   0.000001       EX_val__L_m
579              medium  SAMN07510030   0.000001       EX_pro__L_m

           flux  abundance     metabolite direction
0   -100.000000   0.389803  fe3pyovd_kt_e    import
1     -0.001000   0.389803        uaccg_e    import
2     -0.001952   0.389803            k_e    import
3     -0.003283   0.389803    lysglugly_e    import
5     -0.006383   0.389803       asn__L_e    import
..          ...        ...            ...       ...
569   -0.000033        NaN          zn2_m    import
573   -0.032169        NaN       lys__L_m    import
577   -0.009747        NaN        udcpp_m    import
578   -0.041247        NaN       val__L_m    import
579   -0.011820        NaN       pro__L_m    import

[184 rows x 8 columns], annotations=                   metabolite  \
reaction
EX_26dap__M_e      26dap__M_e
EX_2m35mdntha_e  2m35mdntha_e
EX_2pglyc_e          2pglyc_e
EX_35dnta_e          35dnta_e
EX_4abz_e              4abz_e
...                       ...
EX_prohisglu_m    prohisglu_m
EX_raffin_m          raffin_m
EX_so3_m                so3_m
EX_tre6p_m            tre6p_m
EX_tsul_m              tsul_m

                                                              name  \
reaction
EX_26dap__M_e                        Meso-2,6-Diaminoheptanedioate
EX_2m35mdntha_e  N  2 methyl 3 5 dinitrophenyl  4 methyl 3 5 di...
EX_2pglyc_e                                     2-Phosphoglycolate
EX_35dnta_e                        N N bis 3 5 dinitrotolyl  amine
EX_4abz_e                                          4-Aminobenzoate
...                                                            ...
EX_prohisglu_m              Proline-histidine-glutamine tripeptide
EX_raffin_m                                    Raffinose C18H32O16
EX_so3_m                                                   Sulfite
EX_tre6p_m                      Alpha,alpha'-Trehalose 6-phosphate
EX_tsul_m                                              Thiosulfate

                 molecular_weight  C_number  N_number          sbo  \
reaction
EX_26dap__M_e          190.197060         7         2  SBO:0000247
EX_2m35mdntha_e         15.014640         0         1  SBO:0000247
EX_2pglyc_e            153.007441         2         0  SBO:0000247
EX_35dnta_e             15.014640         0         1  SBO:0000247
EX_4abz_e              136.128040         7         1  SBO:0000247
...                           ...       ...       ...          ...
EX_prohisglu_m         398.391060        16         5  SBO:0000247
EX_raffin_m            504.437080        18         0  SBO:0000247
EX_so3_m                80.063200         0         0  SBO:0000247
EX_tre6p_m             420.260501        12         0  SBO:0000247
EX_tsul_m              112.128200         0         0  SBO:0000247

                        kegg.compound  \
reaction
EX_26dap__M_e                  C00680
EX_2m35mdntha_e                   NaN
EX_2pglyc_e                    C00988
EX_35dnta_e                       NaN
EX_4abz_e                      C00568
...                               ...
EX_prohisglu_m                    NaN
EX_raffin_m                    C00492
EX_so3_m         ['C00094', 'C11481']
EX_tre6p_m                     C00689
EX_tsul_m        ['C00320', 'C05529']

                                                             chebi  \
reaction
EX_26dap__M_e    ['CHEBI:10598', 'CHEBI:12822', 'CHEBI:12823', ...
EX_2m35mdntha_e                                                NaN
EX_2pglyc_e      ['CHEBI:11652', 'CHEBI:1268', 'CHEBI:17150', '...
EX_35dnta_e                                                    NaN
EX_4abz_e        ['CHEBI:113372', 'CHEBI:11959', 'CHEBI:1783', ...
...                                                            ...
EX_prohisglu_m                                                 NaN
EX_raffin_m      ['CHEBI:15015', 'CHEBI:16634', 'CHEBI:26521', ...
EX_so3_m         ['CHEBI:13367', 'CHEBI:15139', 'CHEBI:17137', ...
EX_tre6p_m       ['CHEBI:10201', 'CHEBI:12285', 'CHEBI:15252', ...
EX_tsul_m        ['CHEBI:15242', 'CHEBI:16094', 'CHEBI:26977', ...

                                    inchikey  \
reaction
EX_26dap__M_e    GMKMEZVLHJARHF-SYDPRGILSA-N
EX_2m35mdntha_e                          NaN
EX_2pglyc_e      ASCFNMCAHFUBCO-UHFFFAOYSA-K
EX_35dnta_e                              NaN
EX_4abz_e        ALYNCZNDIQEVRV-UHFFFAOYSA-M
...                                      ...
EX_prohisglu_m                           NaN
EX_raffin_m      MUPFEKGTMRGPLJ-ZQSKZDJDSA-N
EX_so3_m         LSNNMFCWUKXFEE-UHFFFAOYSA-L
EX_tre6p_m       LABSPYBHMPDTEL-LIZSDCNHSA-L
EX_tsul_m        DHCDFWKWKRSZHF-UHFFFAOYSA-M

                                                  biocyc metanetx.chemical  \
reaction
EX_26dap__M_e                  META:MESO-DIAMINOPIMELATE           MNXM529
EX_2m35mdntha_e                                      NaN               NaN
EX_2pglyc_e                                  META:CPD-67          MNXM2074
EX_35dnta_e                                          NaN               NaN
EX_4abz_e                          META:P-AMINO-BENZOATE           MNXM421
...                                                  ...               ...
EX_prohisglu_m                                       NaN               NaN
EX_raffin_m                                META:CPD-1099           MNXM621
EX_so3_m         ['META:H2SO3', 'META:HSO3', 'META:SO3']        MNXM105630
EX_tre6p_m                             META:TREHALOSE-6P           MNXM448
EX_tsul_m                                      META:S2O3           MNXM323

                seed.compound  \
reaction
EX_26dap__M_e        cpd00516
EX_2m35mdntha_e           NaN
EX_2pglyc_e          cpd00727
EX_35dnta_e               NaN
EX_4abz_e            cpd00443
...                       ...
EX_prohisglu_m            NaN
EX_raffin_m          cpd00382
EX_so3_m             cpd00081
EX_tre6p_m           cpd00523
EX_tsul_m            cpd00268

                                                              hmdb kegg.drug  \
reaction
EX_26dap__M_e                                                  NaN       NaN
EX_2m35mdntha_e                                                NaN       NaN
EX_2pglyc_e                             ['HMDB00816', 'HMDB60148']       NaN
EX_35dnta_e                                                    NaN       NaN
EX_4abz_e                                                HMDB01392    D02456
...                                                            ...       ...
EX_prohisglu_m                                                 NaN       NaN
EX_raffin_m                                              HMDB03213       NaN
EX_so3_m         ['HMDB00240', 'HMDB01033', 'HMDB03008', 'HMDB3...       NaN
EX_tre6p_m                                               HMDB01124       NaN
EX_tsul_m                               ['HMDB00257', 'HMDB60293']       NaN

                      reactome lipidmaps kegg.glycan         reaction
reaction
EX_26dap__M_e              NaN       NaN         NaN    EX_26dap__M_e
EX_2m35mdntha_e            NaN       NaN         NaN  EX_2m35mdntha_e
EX_2pglyc_e                NaN       NaN         NaN      EX_2pglyc_e
EX_35dnta_e                NaN       NaN         NaN      EX_35dnta_e
EX_4abz_e                  NaN       NaN         NaN        EX_4abz_e
...                        ...       ...         ...              ...
EX_prohisglu_m             NaN       NaN         NaN   EX_prohisglu_m
EX_raffin_m                NaN       NaN      G00249      EX_raffin_m
EX_so3_m                   NaN       NaN         NaN         EX_so3_m
EX_tre6p_m        R-ALL-868701       NaN      G09795       EX_tre6p_m
EX_tsul_m        R-ALL-1614595       NaN         NaN        EX_tsul_m

[440 rows x 18 columns])

In [12]:
pl = plot_growth(res, filename=f"{out_folder}growth_rates_fixed_medium.html")

In [18]:
from micom.interaction import interactions

ints = interactions(res, taxa='spire_mag_00366776')
ints.sort_values(by="flux", ascending=False).head()

,metabolite,focal,partner,class,flux,sample_id,name,molecular_weight,C_number,N_number,...,inchikey,biocyc,metanetx.chemical,seed.compound,hmdb,kegg.drug,reactome,lipidmaps,kegg.glycan,reaction
1,fe3_e,spire_mag_00366776,spire_mag_00366783,provided,35.754181,SAMN07510030,Iron (Fe3+),55.84500,0,0,...,VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e
3,fe3pyovd_kt_e,spire_mag_00366776,spire_mag_00366783,received,35.754181,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
5,pyovd_kt_e,spire_mag_00366776,spire_mag_00366783,provided,35.754181,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
2,fe3pyovd_kt_e,spire_mag_00366776,spire_mag_00366781,received,3.226061,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
4,pyovd_kt_e,spire_mag_00366776,spire_mag_00366781,provided,3.226061,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e

In [19]:
ints = interactions(res, taxa='spire_mag_00366781')
ints.sort_values(by="flux", ascending=False).head()

,metabolite,focal,partner,class,flux,sample_id,name,molecular_weight,C_number,N_number,...,inchikey,biocyc,metanetx.chemical,seed.compound,hmdb,kegg.drug,reactome,lipidmaps,kegg.glycan,reaction
2,fe3pyovd_kt_e,spire_mag_00366781,spire_mag_00366776,provided,3.226061,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
3,pyovd_kt_e,spire_mag_00366781,spire_mag_00366776,received,3.226061,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
4,pyovd_kt_e,spire_mag_00366781,spire_mag_00366783,co-consumed,3.226061,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
0,fe3_e,spire_mag_00366781,spire_mag_00366776,received,3.226061,SAMN07510030,Iron (Fe3+),55.84500,0,0,...,VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e
1,fe3_e,spire_mag_00366781,spire_mag_00366783,co-consumed,3.226061,SAMN07510030,Iron (Fe3+),55.84500,0,0,...,VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e

In [20]:
ints = interactions(res, taxa='spire_mag_00366783')
ints.sort_values(by="flux", ascending=False).head()

,metabolite,focal,partner,class,flux,sample_id,name,molecular_weight,C_number,N_number,...,inchikey,biocyc,metanetx.chemical,seed.compound,hmdb,kegg.drug,reactome,lipidmaps,kegg.glycan,reaction
28,pyovd_kt_e,spire_mag_00366783,spire_mag_00366776,received,35.754181,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
10,fe3_e,spire_mag_00366783,spire_mag_00366776,received,35.754181,SAMN07510030,Iron (Fe3+),55.84500,0,0,...,VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e
12,fe3pyovd_kt_e,spire_mag_00366783,spire_mag_00366776,provided,35.754181,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
29,pyovd_kt_e,spire_mag_00366783,spire_mag_00366781,co-consumed,3.226061,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
11,fe3_e,spire_mag_00366783,spire_mag_00366781,co-consumed,3.226061,SAMN07510030,Iron (Fe3+),55.84500,0,0,...,VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e

In [22]:
from micom.interaction import summarize_interactions

summary = summarize_interactions(ints)
summary

,sample_id,focal,partner,class,flux,mass_flux,C_flux,N_flux,n_ints
0,SAMN07510030,spire_mag_00366783,spire_mag_00366776,co-consumed,0.085219,0.005463,0.124089,0.033313,29
1,SAMN07510030,spire_mag_00366783,spire_mag_00366776,provided,35.774287,28.910207,965.365220,357.541807,4
2,SAMN07510030,spire_mag_00366783,spire_mag_00366776,received,71.508361,28.909866,965.362878,357.541807,2
3,SAMN07510030,spire_mag_00366783,spire_mag_00366781,co-consumed,6.452123,2.608506,87.103660,32.260615,2

In [24]:
full = interactions(res, taxa=None, threads=8)
full.shape

Output()

(80, 23)

In [30]:
from micom.interaction import MES

scores = MES(res)
scores.sort_values("MES", ascending=False).head()

,metabolite,sample_id,MES,name,molecular_weight,C_number,N_number,sbo,kegg.compound,chebi,inchikey,biocyc,metanetx.chemical,seed.compound,hmdb,kegg.drug,reactome,lipidmaps,kegg.glycan,reaction
22,fe3_e,SAMN07510030,1.333333,Iron (Fe3+),55.84500,0,0,SBO:0000247,C14819,"['CHEBI:13320', 'CHEBI:21130', 'CHEBI:24877', ...",VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e
23,fe3pyovd_kt_e,SAMN07510030,1.333333,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,SBO:0000247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
59,pyovd_kt_e,SAMN07510030,1.333333,Pyoverdine P putida specific,752.72802,27,10,SBO:0000247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
36,h_e,SAMN07510030,1.000000,H+,1.00794,0,0,SBO:0000247,C00080,"['CHEBI:10744', 'CHEBI:13357', 'CHEBI:15378', ...",GPRLSGONYQIRFK-UHFFFAOYSA-N,META:PROTON,MNXM1,cpd00067,HMDB59597,NaN,"['R-ALL-1132304', 'R-ALL-113529', 'R-ALL-14700...",NaN,NaN,EX_h_e
34,h2o_e,SAMN07510030,1.000000,H2O H2O,18.01528,0,0,SBO:0000247,"['C00001', 'C01328']","['CHEBI:10743', 'CHEBI:13352', 'CHEBI:13365', ...",XLYOFNOQVPJJNP-UHFFFAOYSA-N,"['META:CPD-15815', 'META:HYDROXYL-GROUP', 'MET...",MNXM2,"['cpd00001', 'cpd15275', 'cpd27222']","['HMDB01039', 'HMDB02111']","['D00001', 'D06322']","['R-ALL-109276', 'R-ALL-113518', 'R-ALL-113519...",NaN,NaN,EX_h2o_e