In [1]:
import os
import pandas as pd
from micom.viz import plot_growth
from micom.workflows import grow

from micom.qiime_formats import load_qiime_medium
from micom.data import test_medium
from micom.workflows import build, build_database

In [2]:
out_folder = "../data/Lloyd-Price_2019_HMP2IBD/SAMN07510030/simulations/"
plot_folder = "../data/plots/"

In [3]:
tax = pd.read_csv("../data/Lloyd-Price_2019_HMP2IBD/SAMN07510030/sample_manifest.csv")
tax

,Unnamed: 0,id,kingdom,phylum,class,order,family,genus,species,file,sample_id,abundance
0,0,spire_mag_00366776,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Rikenellaceae,Alistipes,Alistipes putredinis,/home/alexandre/Documents/projects/micro_fr_pr...,SAMN07510030,389.802726
1,1,spire_mag_00366781,Bacteria,Bacteroidota,Bacteroidia,Bacteroidales,Bacteroidaceae,Bacteroides,Bacteroides uniformis,/home/alexandre/Documents/projects/micro_fr_pr...,SAMN07510030,252.655467
2,2,spire_mag_00366783,Bacteria,Firmicutes_A,Clostridia,Lachnospirales,Lachnospiraceae,Agathobacter,Agathobacter rectalis,/home/alexandre/Documents/projects/micro_fr_pr...,SAMN07510030,357.541807

In [4]:
manifest = build(
    taxonomy=tax,
    out_folder=f"{out_folder}",
    model_db=None,
    cutoff=0.0001,
    threads=2,
)

manifest

[04/10/25 13:52:02] WARNING  Found existing models for 1 samples. Will skip those. Delete the output    ]8;id=47557;file:///home/alexandre/miniconda3/envs/mtgw/lib/python3.9/site-packages/micom/workflows/build.py\build.py]8;;\:]8;id=160548;file:///home/alexandre/miniconda3/envs/mtgw/lib/python3.9/site-packages/micom/workflows/build.py#98\98]8;;\
                             folder if you would like me to rebuild them.

Output()

Set parameter Username
Set parameter LicenseID to value 2582980
Academic license - for non-commercial use only - expires 2025-11-13
Read LP format model from file /tmp/tmpurs9dbch.lp
Reading time = 0.01 seconds
: 1989 rows, 4791 columns, 18333 nonzeros

      sample_id                 file
0  SAMN07510030  SAMN07510030.pickle

In [5]:
medium = load_qiime_medium("../data/western_diet_gut.qza")
# medium = load_qiime_medium(test_medium)
medium

                flux  dilution metabolite    reaction
reaction
EX_fru_m    0.014899     0.100      fru_m    EX_fru_m
EX_glc_m    0.014899     0.100      glc_m    EX_glc_m
EX_gal_m    0.014899     0.100      gal_m    EX_gal_m
EX_man_m    0.014899     0.100      man_m    EX_man_m
EX_mnl_m    0.014899     0.100      mnl_m    EX_mnl_m
...              ...       ...        ...         ...
EX_glu_D_m  0.100000     0.100    glu_D_m  EX_glu_D_m
EX_gthrd_m  0.100000     0.100    gthrd_m  EX_gthrd_m
EX_h2_m     0.100000     0.100       h2_m     EX_h2_m
EX_no2_m    0.100000     0.100      no2_m    EX_no2_m
EX_o2_m     0.001000     0.001       o2_m     EX_o2_m

[170 rows x 4 columns]

In [6]:
res = grow(
    manifest,
    model_folder=out_folder,
    medium=medium,
    tradeoff=1.0,
    threads=2,
)

Output()

Set parameter Username
Set parameter LicenseID to value 2582980
Academic license - for non-commercial use only - expires 2025-11-13
Read LP format model from file /tmp/tmpjibowqp_.lp
Reading time = 0.01 seconds
: 1989 rows, 4791 columns, 18333 nonzeros

In [7]:
pl = plot_growth(res, filename=f"{plot_folder}growth_rates.html")

In [22]:
import pandas as pd

# candidate_medium = pd.DataFrame({"reaction": ["EX_glc__D_m", "EX_o2_m"], "flux": [10, 20]})
# candidate_medium

candidate_medium = load_qiime_medium(test_medium)
candidate_medium

                reaction       flux metabolite
reaction
EX_glc__D_m  EX_glc__D_m  10.000000   glc__D_m
EX_nh4_m        EX_nh4_m   4.362240      nh4_m
EX_o2_m          EX_o2_m  18.579253       o2_m
EX_pi_m          EX_pi_m   2.942960       pi_m

In [23]:
from micom.workflows import complete_community_medium

medium = complete_community_medium(manifest, model_folder=out_folder, medium=candidate_medium,
                    community_growth=0.1, min_growth=0.01,
                    max_import=10, threads=2)
medium

Output()

Set parameter Username
Set parameter LicenseID to value 2582980
Academic license - for non-commercial use only - expires 2025-11-13
Read LP format model from file /tmp/tmpj6ug2gu2.lp
Reading time = 0.02 seconds
: 1989 rows, 4791 columns, 18333 nonzeros

,reaction,metabolite,description,flux
0,EX_26dap__M_m,26dap__M_m,"Meso-2,6-Diaminoheptanedioate",0.009358
1,EX_2ameph_m,2ameph_m,2-Aminoethylphosphonate,0.001171
2,EX_LalaDgluMdap_m,LalaDgluMdap_m,"L-alanine-D-glutamate-meso-2,6-diaminoheptaned...",0.000253
3,EX_acmana_m,acmana_m,N-Acetyl-D-mannosamine,0.000505
4,EX_acnam_m,acnam_m,N-Acetylneuraminate,0.009358
...,...,...,...,...
65,EX_uaccg_m,uaccg_m,UDP-N-acetyl-3-O-(1-carboxyvinyl)-D-glucosamine,0.009747
66,EX_udcpp_m,udcpp_m,Undecaprenyl phosphate,0.010000
67,EX_ump_m,ump_m,UMP C9H11N2O9P,0.000770
68,EX_val__L_m,val__L_m,L-Valine,0.043454
69,EX_zn2_m,zn2_m,Zinc,0.000034

In [24]:
res = grow(
    manifest,
    model_folder=out_folder,
    medium=medium,
    tradeoff=1.0,
    threads=2,
)

Output()

Set parameter Username
Set parameter LicenseID to value 2582980
Academic license - for non-commercial use only - expires 2025-11-13
Read LP format model from file /tmp/tmpvwhrm2xb.lp
Reading time = 0.02 seconds
: 1989 rows, 4791 columns, 18333 nonzeros

In [25]:
pl = plot_growth(res, filename=f"{plot_folder}growth_rates_fixed_medium.html")
pl.view()

In [12]:
# from micom.viz import plot_exchanges_per_taxon

#pl = plot_exchanges_per_taxon(res, filename=f"{out_folder}niche.html")
#pl.view()

In [26]:
from micom.interaction import interactions

ints = interactions(res, taxa='spire_mag_00366776')
ints.sort_values(by="flux", ascending=False).head()

,metabolite,focal,partner,class,flux,sample_id,name,molecular_weight,C_number,N_number,...,inchikey,biocyc,metanetx.chemical,seed.compound,hmdb,kegg.drug,reactome,lipidmaps,kegg.glycan,reaction
0,fe3pyovd_kt_e,spire_mag_00366776,spire_mag_00366781,co-consumed,10.488634,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
1,fe3pyovd_kt_e,spire_mag_00366776,spire_mag_00366783,received,10.488634,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
28,pyovd_kt_e,spire_mag_00366776,spire_mag_00366783,provided,10.488634,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
12,fe3_e,spire_mag_00366776,spire_mag_00366783,provided,10.488604,SAMN07510030,Iron (Fe3+),55.84500,0,0,...,VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e
26,o2_e,spire_mag_00366776,spire_mag_00366783,co-consumed,0.068996,SAMN07510030,O2 O2,31.99880,0,0,...,MYMOFIZGZYHOMD-UHFFFAOYSA-N,META:OXYGEN-MOLECULE,MNXM4,cpd00007,HMDB01377,D00003,"['R-ALL-1131511', 'R-ALL-113533', 'R-ALL-11353...",NaN,NaN,EX_o2_e

In [14]:
ints = interactions(res, taxa='spire_mag_00366781')
ints.sort_values(by="flux", ascending=False).head()

,metabolite,focal,partner,class,flux,sample_id,name,molecular_weight,C_number,N_number,...,inchikey,biocyc,metanetx.chemical,seed.compound,hmdb,kegg.drug,reactome,lipidmaps,kegg.glycan,reaction
2,fe3pyovd_kt_e,spire_mag_00366781,spire_mag_00366776,provided,3.226061,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
3,pyovd_kt_e,spire_mag_00366781,spire_mag_00366776,received,3.226061,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
4,pyovd_kt_e,spire_mag_00366781,spire_mag_00366783,co-consumed,3.226061,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
0,fe3_e,spire_mag_00366781,spire_mag_00366776,received,3.226061,SAMN07510030,Iron (Fe3+),55.84500,0,0,...,VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e
1,fe3_e,spire_mag_00366781,spire_mag_00366783,co-consumed,3.226061,SAMN07510030,Iron (Fe3+),55.84500,0,0,...,VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e

In [27]:
ints = interactions(res, taxa='spire_mag_00366783')
ints.sort_values(by="flux", ascending=False).head()

,metabolite,focal,partner,class,flux,sample_id,name,molecular_weight,C_number,N_number,...,inchikey,biocyc,metanetx.chemical,seed.compound,hmdb,kegg.drug,reactome,lipidmaps,kegg.glycan,reaction
30,pyovd_kt_e,spire_mag_00366783,spire_mag_00366781,received,25.265547,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
11,fe3_e,spire_mag_00366783,spire_mag_00366781,received,25.265547,SAMN07510030,Iron (Fe3+),55.84500,0,0,...,VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e
13,fe3pyovd_kt_e,spire_mag_00366783,spire_mag_00366781,provided,25.265547,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
12,fe3pyovd_kt_e,spire_mag_00366783,spire_mag_00366776,provided,10.488634,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
29,pyovd_kt_e,spire_mag_00366783,spire_mag_00366776,received,10.488634,SAMN07510030,Pyoverdine P putida specific,752.72802,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e

In [28]:
from micom.interaction import summarize_interactions

summary = summarize_interactions(ints)
summary

,sample_id,focal,partner,class,flux,mass_flux,C_flux,N_flux,n_ints
0,SAMN07510030,spire_mag_00366783,spire_mag_00366776,co-consumed,0.085219,0.005463,0.124089,0.033313,29
1,SAMN07510030,spire_mag_00366783,spire_mag_00366776,provided,10.508740,8.481168,283.195458,104.886339,4
2,SAMN07510030,spire_mag_00366783,spire_mag_00366776,received,20.977237,8.480825,283.193116,104.886339,2
3,SAMN07510030,spire_mag_00366783,spire_mag_00366781,provided,25.265547,20.429039,682.169762,252.655467,1
4,SAMN07510030,spire_mag_00366783,spire_mag_00366781,received,50.531093,20.429039,682.169762,252.655467,2

In [29]:
full = interactions(res, taxa=None, threads=8)
full.shape

full

Output()

,metabolite,focal,partner,class,flux,sample_id,name,molecular_weight,C_number,N_number,...,inchikey,biocyc,metanetx.chemical,seed.compound,hmdb,kegg.drug,reactome,lipidmaps,kegg.glycan,reaction
0,fe3pyovd_kt_e,spire_mag_00366781,spire_mag_00366776,co-consumed,10.488634,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.573020,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
1,fe3pyovd_kt_e,spire_mag_00366781,spire_mag_00366783,received,25.265547,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.573020,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
2,fe3_e,spire_mag_00366781,spire_mag_00366783,provided,25.265547,SAMN07510030,Iron (Fe3+),55.845000,0,0,...,VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e
3,pyovd_kt_e,spire_mag_00366781,spire_mag_00366783,provided,25.265547,SAMN07510030,Pyoverdine P putida specific,752.728020,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
0,fe3pyovd_kt_e,spire_mag_00366776,spire_mag_00366781,co-consumed,10.488634,SAMN07510030,Ferrypyoverdine P putida KT2440 specific,808.573020,27,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,tyr__L_e,spire_mag_00366783,spire_mag_00366776,co-consumed,0.000537,SAMN07510030,L-Tyrosine,181.188540,9,1,...,OUYCCCASQSFEME-QMMMGPOBSA-N,META:TYR,MNXM76,"['cpd00069', 'cpd30745']","['HMDB00158', 'HMDB00647']",D00022,"['R-ALL-29506', 'R-ALL-352030', 'R-ALL-379710'...",NaN,NaN,EX_tyr__L_e
34,uaccg_e,spire_mag_00366783,spire_mag_00366776,co-consumed,0.000390,SAMN07510030,UDP-N-acetyl-3-O-(1-carboxyvinyl)-D-glucosamine,674.376662,20,3,...,BEGZZYPUNCJHKP-DBYWSUQTSA-K,META:UDP-ACETYL-CARBOXYVINYL-GLUCOSAMINE,MNXM1688,cpd02820,NaN,NaN,NaN,NaN,NaN,EX_uaccg_e
35,udcpp_e,spire_mag_00366783,spire_mag_00366776,co-consumed,0.000390,SAMN07510030,Undecaprenyl phosphate,846.274461,55,0,...,UFPHFKCTOZIAFY-RDQGWRCRSA-L,META:UNDECAPRENYL-P,MNXM251,cpd00286,NaN,NaN,NaN,LMPR03020006,NaN,EX_udcpp_e
36,val__L_e,spire_mag_00366783,spire_mag_00366776,co-consumed,0.001649,SAMN07510030,L-Valine,117.146340,5,1,...,KZSNJWFQEVHDMF-BYPYZUCNSA-N,META:VAL,MNXM199,"['cpd00156', 'cpd15141']","['HMDB00883', 'HMDB34366']",D00039,"['R-ALL-113540', 'R-ALL-29702']",LMFA01100046,NaN,EX_val__L_e
37,zn2_e,spire_mag_00366783,spire_mag_00366776,co-consumed,0.000001,SAMN07510030,Zinc,65.409000,0,0,...,PTFCDOFLOPIGGS-UHFFFAOYSA-N,META:ZN+2,MNXM149,cpd00034,HMDB01303,NaN,"['R-ALL-158417', 'R-ALL-216667', 'R-ALL-216785...",NaN,NaN,EX_zn2_e

In [18]:
from micom.viz import plot_focal_interactions

pl = plot_focal_interactions(res, taxon="spire_mag_00366781", filename=f"{plot_folder}niche.html")
pl.view()

In [19]:
from micom.interaction import MES

scores = MES(res)
scores.sort_values("MES", ascending=False).head()

,metabolite,sample_id,MES,name,molecular_weight,C_number,N_number,sbo,kegg.compound,chebi,inchikey,biocyc,metanetx.chemical,seed.compound,hmdb,kegg.drug,reactome,lipidmaps,kegg.glycan,reaction
22,fe3_e,SAMN07510030,1.333333,Iron (Fe3+),55.84500,0,0,SBO:0000247,C14819,"['CHEBI:13320', 'CHEBI:21130', 'CHEBI:24877', ...",VTLYFUHAOXGGBS-UHFFFAOYSA-N,META:FE+3,MNXM196,cpd10516,HMDB12943,NaN,"['R-ALL-111736', 'R-ALL-912516', 'R-ALL-912519...",NaN,NaN,EX_fe3_e
23,fe3pyovd_kt_e,SAMN07510030,1.333333,Ferrypyoverdine P putida KT2440 specific,808.57302,27,10,SBO:0000247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_fe3pyovd_kt_e
59,pyovd_kt_e,SAMN07510030,1.333333,Pyoverdine P putida specific,752.72802,27,10,SBO:0000247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EX_pyovd_kt_e
36,h_e,SAMN07510030,1.000000,H+,1.00794,0,0,SBO:0000247,C00080,"['CHEBI:10744', 'CHEBI:13357', 'CHEBI:15378', ...",GPRLSGONYQIRFK-UHFFFAOYSA-N,META:PROTON,MNXM1,cpd00067,HMDB59597,NaN,"['R-ALL-1132304', 'R-ALL-113529', 'R-ALL-14700...",NaN,NaN,EX_h_e
34,h2o_e,SAMN07510030,1.000000,H2O H2O,18.01528,0,0,SBO:0000247,"['C00001', 'C01328']","['CHEBI:10743', 'CHEBI:13352', 'CHEBI:13365', ...",XLYOFNOQVPJJNP-UHFFFAOYSA-N,"['META:CPD-15815', 'META:HYDROXYL-GROUP', 'MET...",MNXM2,"['cpd00001', 'cpd15275', 'cpd27222']","['HMDB01039', 'HMDB02111']","['D00001', 'D06322']","['R-ALL-109276', 'R-ALL-113518', 'R-ALL-113519...",NaN,NaN,EX_h2o_e

In [20]:
from micom.viz import plot_mes

pl = plot_mes(res, filename=f"{plot_folder}mes.html")
pl.view()